name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Linter (Code Style Check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install black flake8

      - name: Run flake8 (Python Lint)
        run: flake8 .

      - name: Run black (Code Formatting Check)
        run: black --check .
